# Generated by Django 3.2.9 on 2021-11-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease_app', '0003_auto_20211129_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_stored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Pred')),
            ],
        ),
        migrations.DeleteModel(
            name='Last_login_user',
        ),
        migrations.AlterField(
            model_name='predicted_label',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_disease_app.image_stored'),
        ),
    ]
