# Generated by Django 3.2.9 on 2021-11-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease_app', '0004_auto_20211129_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicted_label',
            old_name='disease',
            new_name='label',
        ),
    ]
